# Generated by Django 3.2.12 on 2023-09-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prodmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=30)),
                ('PBrand', models.CharField(max_length=30)),
                ('PPrice', models.IntegerField(default=50)),
                ('Stock', models.CharField(max_length=30)),
            ],
        ),
    ]
